[package]
name = "cb-plugin-api"
version = "1.0.1-beta"
edition = "2021"

[build-dependencies]
serde = { workspace = true }
toml = "0.9"

[dependencies]
cb-types = { path = "../cb-types" }
cb-core = { path = "../cb-core" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }