[package]
name = "mill-lang-go"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
# Mill workspace dependencies
mill-plugin-api = { path = "../../crates/mill-plugin-api" }
mill-foundation = { path = "../../crates/mill-foundation" }
mill-lang-common = { path = "../../crates/mill-lang-common" }

# Async operations
async-trait = { workspace = true }
tokio = { workspace = true }

# Serialization/Deserialization & Other Utilities
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
regex.workspace = true
chrono = { version = "0.4", features = ["serde"] }

# Error handling
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }
pathdiff = "0.2.3"
which = "8.0.0"

[dev-dependencies]
tempfile = "3.10"
